version: "3.9"

services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-builder-lab1
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php82-service
    networks:
      - nginx-php82

  php82-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php82-builder-lab1
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php82

networks:
  nginx-php82:
    driver: bridge
    name: nginx-php82
    ipam:
      driver: default
      config:
        - subnet: 172.36.0.0/25
